###
GET http://localhost:3000/routes

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "title": "minha rota",
    "startPosition": { "lat": 1, "lng": 2 },
    "endPosition": { "lat": 1, "lng": 2 }
}